%% Set parameters
bat_list = {'Tb90'};
data_location='S:\Smotherman_Lab\Auditory cortex\';
sr = 40000;
[b,a] = butter(4,[800/(sr/2), 3000/(sr/2)],'bandpass');
channels_available=32;
save_path='C:\Users\kbakshi\Documents\Data\STRF Analysis\';
MTF_save_path = 'U:\STRF Analysis\TMR and SMR\';
shank_pos=xlsread('Shank Position.xlsx');
strf_table(1,:) = {'Bat', 'Experimental_Site', 'RC_Location', 'Depth', 'Peak_Excitatory_Frequency',...
    'Latency_At_Peak', 'Peak_Firing_Rate', 'Excitatory_Spectral_BW', 'Excitatory_Temporal_BW',...
    'Inhibitory_Spectral_BW', 'Inhibitory_Temporal_BW', 'Spectral_max_MTF',...
    'Temporal_max_MTF', 'Spectral_cutoff_MTF', 'Temporal_cutoff_MTF'};
iter = 2;

for bat_num = 1:numel(bat_list)
    d = dir(strjoin([data_location,bat_list(:,1),'\Matfile'],''));
    site_number = numel(d)-2;
    for site = 4 %1:site_number
        %% Import Data, preprocess, and extract spike times
        load(strjoin([data_location,string(bat_list(:,bat_num)),'\Matfile\',...
            d(site+2,1).name,'\event.mat'],''));
        cutoff = ts(end)*sr;
        marker = importdata(strjoin([data_location,string(bat_list(:,bat_num)),...
            '\Data\',string(bat_list(:,bat_num)),'_',num2str(site),'_marker_tc.mat'],''));
        for channel = 1:channels_available
            if isfile(strjoin([data_location,string(bat_list(:,bat_num)),'\Matfile\',...
                    d(site+2,1).name,'\Chn',num2str(channel),'.mat'],''))
                
                readfile = matfile(strjoin([data_location,string(bat_list(:,bat_num)),...
                    '\Matfile\',d(site+2,1).name,'\Chn',num2str(channel),'.mat'],''));
                data = readfile.data;
                data(1:cutoff) = [];
                data = filtfilt(b,a,data);
                thr = std(data)*4;
                [peaks,locs] = findpeaks(data*-1,'MinPeakHeight',thr);
                locs = (locs/sr)*1000;
                depth = marker.depth-shank_pos(channel,1);
                %% Find STRF
                spk = locs;
                spiketimes{1}=spk;
                processdata
                STA=DMRcells.STA;
                STA_avg=mean(STA(:));
                STA_stdev=std(STA(:))*3;
                minus_STA_stdev=STA_stdev*-1;
                STA(STA > minus_STA_stdev & STA < STA_stdev) = 0;
                [col,row]=find(STA==max(STA(:)));
                latency=taxis(row);
                peak_freq=faxis(col)/1000;
                [col,row]=find(STA==min(STA(:)));
                min_peak_freq = faxis(col)/1000;
                min_latency = taxis(row);
                [e_spectralBW, e_temporalBW, i_spectralBW, i_temporalBW] = findSTRFbw(STA, taxis, faxis);
                %% Create STRF Figure
                [fig1, maxFR] = plotMuASTRF(STA, taxis, faxis, X, depth,...
                    latency, peak_freq, site, channel);
               exportgraphics(fig1,...
                   strjoin([save_path,string(bat_list(:,bat_num)),...
                   '\Site ',num2str(site),' Chn ',num2str(channel),' STRF.jpg'],''),...
                   'Resolution', 300)
                save(strjoin([save_path,string(bat_list(:,bat_num)),...
                    '\Site ',num2str(site),' Chn ',num2str(channel),' STA'],''),...
                    'STA')
                save(strjoin([save_path,string(bat_list(:,bat_num)),...
                    '\Site ',num2str(site),' Chn ',num2str(channel),' faxis'],''),...
                    'faxis')
                save(strjoin([save_path,string(bat_list(:,bat_num)),...
                    '\Site ',num2str(site),' Chn ',num2str(channel),' taxis'],''),...
                    'taxis')
                %% Generate modulation functions
                [MTF, tempmod, specmod] = STRF2MTF(STA, taxis, X);
                [fig2, specmod_max, tempmod_max, specmod_cut, tempmod_cut] = plotMTF(MTF, tempmod, specmod);
                sgtitle(['Site ',num2str(site), ' Chn ',num2str(channel),' MUA MTF'], 'Fontweight', 'bold')
                exportgraphics(fig2,...
                    strjoin([save_path,string(bat_list(:,bat_num)),...
                    '\Site ',num2str(site),' Chn ',num2str(channel),' MTF.jpg'],''),...
                    'Resolution', 300)
                save(strjoin([save_path,string(bat_list(:,bat_num)),...
                    '\Site ',num2str(site),' Chn ',num2str(channel),' MTF'],''),...
                    'MTF')
                save(strjoin([save_path,string(bat_list(:,bat_num)),...
                    '\Site ',num2str(site),' Chn ',num2str(channel),' specmod'],''),...
                    'specmod')
                save(strjoin([save_path,string(bat_list(:,bat_num)),...
                    '\Site ',num2str(site),' Chn ',num2str(channel),' tempmod'],''),...
                    'tempmod')
                close all
               
                strf_table(iter,:) = {bat_list(bat_num),...
                    ['Site ', num2str(site), 'Channel ', num2str(channel)],...
                    marker.rostro_caudal, depth, peak_freq, latency, maxFR, e_spectralBW,...
                    e_temporalBW, i_spectralBW, i_temporalBW, specmod_max,...
                    tempmod_max, specmod_cut, tempmod_cut};
               iter = iter+1;     
            end
            clearvars -except bat_list data_location sr b a...
                channels_available channel save_path...
                ts marker shank_pos d site bat_num cutoff strf_table...
                iter
        end

    end
end
save([save_path, 'STRF_data_full.mat'], 'strf_table')